### ISSUE TITLE
MOB_rotateToLandscapeToDraw not hiding on iPhone

### ISSUE THREAD

**Issue by robertWeller** [docusign/DocuSign-.NET-Client#67]
So on the mobile embedded iframe if I rotate the screen to draw a signature on android everything works fine. I can draw or accept a template signature and move on with the rest of the form.

However, on the iPhone the div MOB_rotateToLandscapeToDraw never removes itself on landscape mode, almost like it never detects it that it is in landscape mode. The options are hidden only because of the div and using dev tools if I make it hidden everything looks great.

![image](https://cloud.githubusercontent.com/assets/6775652/11314893/2f8e810a-8fb8-11e5-9cac-e6e89cb5d1ff.png)

Due to cross domain securities I can't use something like jquery to remove this on my own and the client does not want an app, so I can't use a webview to solve this like suggested on the docusign site, so any suggestions?

**Comment by stephenparish** [comment]
Hi @robertWeller, this usually happens due to a bug with iframes on iOS Safari. From what we've seen, the iframe does not resize after a rotate, which causes the iframe to actually be taller than it is wide (running slightly below the fold). 
It being those dimensions forces the Draw a Signature screen to think that the device is still in portrait.

The fix we recommend is to listen to a window resize event through javascript and update the size of the iframe manually due to the iframe not respecting width and height percentages via CSS.

**Comment by robertWeller** [comment]
You are a gentleman and scholar!

I used jquery to change the frames height to match the window height which suited my needs.

Thanks again!
