### ISSUE TITLE
Send On Behalf Of isn't sent in some methods

### ISSUE THREAD

**Issue by joepetrakovich** [docusign/DocuSign-.NET-Client#69]
I noticed the part where the accounts SOBOUserID field is attached to the request is only in some but not all methods.  Is there a reason for this?  For example the basic Envelope.Create method that accepts a filepath does not do it, but the other versions do.  Same with the Account.LoginDirect method.

**Comment by InbarGazit** [comment]
@joepetrakovich are you using SOBO for your solution? I'm just curious to see if you're actually using this capability. I suspect SOBOUserID is missing from some things simply because we didn't use it for our integrations and forgot to add it. We can certainly add it to Envelope.Create()
As for LoginDirect() I'm not sure that makes sense. can you explain why you would need it there? SOBO is a mechanism of using 1 user for authentication while sending on behalf of another user, so that you don't actually need to login anyone else. Care to elaborate about your scenario?

**Comment by joepetrakovich** [comment]
@InbarGazit Yeah I believe we will need to use SOBO in our solution, that's what someone from DocuSign told us anyway, I'm just the developer in the trenches ;)

I think my mistake was assuming it needed to be added to both login and envelope creation.  Apparently not!  So really the issue I'm bringing up is that SOBO is left out of Envelope.Create(filePath).

It also seems to be left out if the authentication format is XML.
